general:
  auth:
    default: default-profile
    ap-east-1: ap-east-1-profile
    me-south-1: me-south-1-profile
    af-south-1: af-south-1-profile
    eu-south-1: eu-south-1-profile
    ap-southeast-3: ap-southeast-3-profile
project:
  s3_bucket: aws-ia
  regions:
    - us-east-1
    - us-west-1
    - ap-east-1
    - me-south-1
    - af-south-1
    - eu-south-1
    - ap-southeast-3
tests:
  test1: {}