general:
  auth:
    default: default-profile
    af-south-1: af-south-1-profile
    ap-east-1: ap-east-1-profile
    ap-southeast-3: ap-southeast-3-profile
    eu-south-1: eu-south-1-profile
    me-south-1: me-south-1-profile
project:
  s3_regional_buckets: true
  s3_bucket: aws-ia
  regions:
    - af-south-1
    - ap-east-1
    - ap-southeast-3
    - eu-south-1
    - me-south-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
    - eu-west-1
    - eu-west-2
    - eu-west-3
    - sa-east-1
    - ap-northeast-1
    - ap-northeast-2
    - ap-northeast-3
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-north-1
tests:
  test1: {}